### PR TITLE
various ellipsoid speedups

### PR DESCRIPTION
**Pull request by segasai**
tensordot is not needed

### CODE REVIEW

**Comment by segasai** [comment]
This set of commits speeds up various ellipsoid things. The effective speedup of update() with bootstrap is ~ 20%. The test is below

```import dynesty.bounding as db
import time
import numpy as np

np.random.seed(1)

points = np.random.normal(size=(100, 10))
e0 = db.Ellipsoid(np.ones(10), np.eye(10))
e1 = db.MultiEllipsoid([e0])
t1 = time.time()
for i in range(1000):
    e1.update(points, bootstrap=10)
t2 = time.time()
print(t2 - t1)

```
I also bit the bullet and ran bounding through yapf, to avoid occasional whitespace changes in the future (when I edit the code is automatically yapf it)

**Comment by joshspeagle** [comment]
Are these changes ~stable enough that I should start to look over this PR for merging in?

**Comment by segasai** [comment]
Yes, It' stable. It also has fixes to the likelihood saving (which broke pool functionality in the main branch).

**Comment by segasai** [comment]
Did you have a chance of looking at this to merge ? I don't want to start changing other things before this is merged, due to potential conflicts.

**Comment by joshspeagle** [comment]
No, sorry -- it's been a crazy busy week on my end. It's on the top of my to-do list, so I plan to do it by the end of the night (Eastern time) at the latest. Sorry about the delay.

**Comment by segasai** [comment]
Thanks!

**Pull request merged**
