### PR TITLE
update error message if trying to get bounding ellipse of a single point

### PR DESCRIPTION
**Pull request by segasai**
Helps #302

### CODE REVIEW

**Comment by segasai** [comment]
Hi, This branch is ready to be merged (it has a collection of various things that'd be nice to merge) 
I want to bring to particular attention this commit  54e268eeeb2d0e1551dbf2ff30d4020583d92199
as it fixes an annoying bug that I've introduced a couple of months ago in the update_interval calculation logic.

**Comment by joshspeagle** [comment]
How is this looking? Can I looking into merging this in? I also want to push the fix to https://github.com/joshspeagle/dynesty/commit/54e268eeeb2d0e1551dbf2ff30d4020583d92199 that we missed and get the updated version on `pip` sooner rather than later.

**Comment by segasai** [comment]
I think this is good to merge, with the only concern over the factor of two in front of the variance calculation (see another issue). If you are happy with that, I think this can be merged. (there is one more function where I'd like to reuse the compute_integrals(), but I can do it in a separate commit later)

**Comment by joshspeagle** [comment]
Okay, then let me look into resolving that first, we can add it in, and then merge.

**Comment by segasai** [comment]
Great! 
Thanks

**Pull request merged**
