### PR TITLE
Slice sampling fix 

### PR DESCRIPTION
**Pull request by segasai**
I've needed an urgent fix to #250 since my codes were crashing regularly, so here is a possible fix. 
I'm not sure that's the best possible fix, but I think it does the job.
Basically it adds optional arguments for propose_*() 
And for the propose_live it accepts a subset of indices. It also avoids the repeated loglikelihood calls. 
There is a bit of a leakage of abstractions, as an if statement is needed to provide different arguments to propose functions depending on which sampler method is used, but maybe it can be refactored later.
The patch include some white space changed due to yapfing of previously un-yapfed nestedsamplers.py
The patch is based on the #257 commit branch.

### CODE REVIEW

**Comment by joshspeagle** [comment]
I was working on something this earlier morning, but let me see if what you have is good enough for now. Will review it shortly.

**Comment by segasai** [comment]
I'm happy with other ways of fixing it, I've just urgently needed to plug this hole. (there could be additonal bugs there)

**Comment by joshspeagle** [comment]
Okay, I actually like your fix better than what I had implemented (mine was done internally without the use of args using the internal live point states). The ability to pass args or lists could be useful to build on in the future if we want to make more changes, plus it just makes everything more explicit (e.g., flagged by method) and avoids more duplication. I'm happy to merge this in once tests have completed.

**Comment by segasai** [comment]
Okay, then I'm happy with the merging. I've added a bit more comments as well (no need to wait for the tests from those)

**Pull request merged**
