### PR TITLE
add pylint test to the test suite to catch trivial oversights

### PR DESCRIPTION
**Pull request by segasai**
To ensure the most obvious errors are caught, I've added pylint to the travis testing.

### CODE REVIEW

**Comment by joshspeagle** [comment]
Looks like this has some particular problem with CI that is causing the build the fail.

**Comment by segasai** [comment]
It's because I based on the branch without the last PR that you merged.

**Comment by joshspeagle** [comment]
Ah okay, will merge this in then.

**Comment by joshspeagle** [comment]
The `pylint` call looks like it breaks for [Python 2.7](https://travis-ci.com/github/joshspeagle/dynesty/jobs/494617139#L420) due to a missing config file (it works in [Python 3.6+](https://travis-ci.com/github/joshspeagle/dynesty/jobs/494617140#L398)). Everything else about the code appears to work fine though.

**Comment by segasai** [comment]
To be honest 2.7 is EOL. Personally I'd retire it completely.

**Pull request merged**
