### PR TITLE
Plotting updated with Python 3 compatibility (isinstance calls updated with try: to avoid types AttributeError)

### PR DESCRIPTION
**Pull request by DanViolette**

### CODE REVIEW

**Comment by DanViolette** [comment]
Plotting works with Python3, should review for Python2 before merger

**Comment by joshspeagle** [comment]
As we discussed, I'll add this fix into the code during the next update, although with some cleaner syntax than used here. I'll keep this pull request open until then.

**Comment by joshspeagle** [comment]
This has now been merged as of 4ccaf1a7cbd47d782b1bd29b0f842dd0b0585e8b.

**Comment by DanViolette** [comment]
Thanks!

**Pull request closed without merging**
